### ISSUE TITLE
`make bootstrap` is failing due to missing build dependences

### ISSUE THREAD

**Issue by bmtcril** [openfun/ralph#246]
## Bug Report

Hi all, I'm excited to get started developing with Ralph. Getting set up I ran into an issue, however. On the master branch `make bootstrap` errors out pip installing psutil due to gcc not being available.

**Expected behavior/code**
`make bootstrap` builds the docker images cleanly.

**Actual Behavior**
An error occurs:

```
#0 22.22       creating build/temp.linux-aarch64-cpython-39/psutil
#0 22.22       gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=594 -DPy_LIMITED_API=0x03060000 -DPSUTIL_LINUX=1 -DPSUTIL_ETHTOOL_MISSING_TYPES=1 -I/usr/local/include/python3.9 -c psutil/_psutil_common.c -o build/temp.linux-aarch64-cpython-39/psutil/_psutil_common.o
#0 22.22       C compiler or Python headers are not installed on this system. Try to run:
#0 22.22       sudo apt-get install gcc python3-dev
#0 22.22       error: command 'gcc' failed: No such file or directory
```

**Steps to Reproduce**
1. Sync the Ralph master branch
2. run `make bootstrap`
3. The above error occurs

**Environment**
- Ralph version: master branch
- Platform: Docker Desktop on Mac OS 13.0.1

**Possible Solution**
I was able to get a successful build by adding the required development tools, see the PR here: https://github.com/bmtcril/ralph/pull/1

**Comment by jmaupetit** [comment]
Thanks for your feedback! :heart: 

I cannot reproduce this behavior, not sure if it's platform-specific or not.

1. Did you add a new dependency before trying to build / bootstrap?
2. Can you provide the full building logs?
3. Which version of Docker + compose are you running?

**Comment by bmtcril** [comment]
Thanks for the reply @jmaupetit ...

1. No new dependencies, just pulled master and ran `make bootstrap`
2. It's pretty long, but I just reproduced it. Here's a gist with the log: https://gist.github.com/bmtcril/6f5b5653318a7baf045750eee73bc079
3. Docker Desktop for Mac, `Docker version 20.10.21, build baeda1f`, `Docker Compose version v2.13.0`

**Comment by jmaupetit** [comment]
Ok, after digging a bit with colleagues using M1 Mac laptops, it occurs that it is linked to this specific architecture. Adding `platform: linux/amd64` to the `app` service in the `docker-compose` file seems to fix the issue:

```yaml
# docker-compose.yml

# [...]
services:
  app:
    platform: linux/amd64
    # [...]
```

Can you confirm this?

**Comment by bmtcril** [comment]
This does work, but forces the image to run in emulation which is bad for performance and can exhibit bugs. An alternative to the fix I proposed, if the concern is build speed, is to wrap it in a conditional. I've confirmed this only installs the necessary packages on the correct platform (line 53 in Dockerfile):

```
# Only the M1 Mac images need these packages installed
ARG TARGETPLATFORM
RUN if [ "$TARGETPLATFORM" = "linux/arm64" ]; \
    then apt-get update && \
        apt-get install -y \
        build-essential \
        gcc \
        python-dev && \
        rm -rf /var/lib/apt/lists/*; \
    fi;

```

**Comment by jmaupetit** [comment]
Ok, then, let's do it this way! Can you submit your PR please?

Thanks again for this feedback. M1 Mac users will thank you :heart:
