### ISSUE TITLE
Add support for custom S3 endpoint

### ISSUE THREAD

**Issue by igobranco** [openfun/ralph#284]
## Feature Request

Add support to read the tracking logs from any S3 compatible service.

We at [NAU](https://www.nau.edu.pt) use Ceph S3. The default Tutor installation uses the [MinIO](https://www.minio.io) to store the files. For example some installations could use that MinIO installation to store the tracking logs, or use other service that provides the same interface.

**Is your feature request related to a problem or unsupported use case? Please describe.**
Add a configuration that allow to change the default AWS S3 endpoint URL to any endpoint URL.

**Describe the solution you'd like**
Change the backend S3 code with a new optional configuration that allow to change the boto3 `endpoint_url`.

**Describe alternatives you've considered**
Any.

**Discovery, Documentation, Adoption, Migration Strategy**
Add a sub-section in the docs to reference that you can use any S3 compatible service, like Ceph S3 or MinIO.

**Do you want to work on it through a Pull Request?**

Yes, me directly, or someone from NAU team.

**Comment by jmaupetit** [comment]
That would be a great improvement indeed @igobranco. Thanks for the report and your future contribution.
