### ISSUE TITLE
Remove "field" as suffix from class names ?

### ISSUE THREAD

**Issue by Leobouloc** [openfun/ralph#301]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
Many classes in code base are named with the suffix "Field" (`LaxObjectField`, `MboxSha1SumActorField(BaseActorField)`, etc.). I would tend to not include this suffix for two reasons: 
1) as it does not describe the object itself
2) I find it a bit confusing, and makes the code harder to read

**Describe the solution you'd like**
I suggest removing these suffixes if possible.

**Comment by quitterie-lcs** [comment]
Thanks @Leobouloc for your feedback.
This issue will be fixed with the PR #294
