### ISSUE TITLE
Plugin management system for Ralph

### ISSUE THREAD

**Issue by Ardawo** [openfun/ralph#329]
## Purpose

Reference on @jmaupetit issue #219 
Inpiration from commit openfun/warren/pull/7

### Proposal and Questions

Each backend is a plugin
Each plugin has it own pyproject.toml
Core directory with pyproject.toml
Find a way to manage update of core with update of plugins
Use of importlib (importlib_metadata or importlib.metadata depending on python version)
Install plugin through pip
New version pattern for plugins
Which entry points ? 
fs => builtin per default ?
When register plugins => check performances

### Next Version

Use of Cookiecutter to bootsrap project efficiently ?

**_Still editing..._**

**Comment by quitterie-lcs** [comment]
Redundant with #219
