### ISSUE TITLE
Incorrect headers when requesting with LRSHTTP backend

### ISSUE THREAD

**Issue by wilbrdt** [openfun/ralph#350]
## Bug Report

**Expected behavior/code**
`LRSHTTP` backend should be able to request any LRS.
With `lrsql`, every request requires the header: `"X-Experience-API-Version":"1.0.3"`.

**Actual Behavior**
Currently, when requesting `lrsql` through the `LRSHTTPBackend`, it returns a `400 Bad Request`.
I dug a little and it seems that: 
- headers are not exported from the `LRSHeaders` pydantic model, so we are passing an instance of `LRSHeaders` to the `httpx` `Client`
- an export with `.dict()` does not create correct headers as it would export them as:
```
{"X_EXPERIENCE_API_VERSION":"1.0.3",
"CONTENT_TYPE":"application/json"}
```
instead of 
```
{"X-Experience-API-Version":"1.0.3",
"content_type":"application/json"}
```

**Steps to Reproduce**
1. Clone [LBT](https://github.com/openfun/lbt)
2. `make run-lrs-lrsql`
3. Add the line `network_mode: host` inside the `app` service under the Ralph `docker-compose.yml`
4. `bin/ralph fetch -b lrs --lrs-base-url http://0.0.0.0:8090 --lrs-username AAA --lrs-password BBB --lrs-statements-endpoint "xapi/statements"`

Note that it works correctly with the following command where we don't use default headers:
`bin/ralph fetch -b lrs --lrs-base-url http://0.0.0.0:8090 --lrs-username AAA --lrs-password BBB --lrs-statements-endpoint "xapi/statements" --lrs-headers "X-Experience-API-Version"="1.0.3"`

**Environment**
- Ralph version: 3.7.0/3.8.0
- Platform: Ubuntu

**Comment by Leobouloc** [comment]
Thank you for the investigation !

This will be fixed by https://github.com/openfun/ralph/pull/348 by adding aliases to `LRSHeaders`.
