### ISSUE TITLE
500 error when passing wrong query parameters to /xAPI/statements

### ISSUE THREAD

**Issue by lebrunthibault** [openfun/ralph#375]
## Bug Report

**Expected behavior/code**
The GET query : `/xAPI/statements?toto=2` should return either a 200 response with no statements or a 400 response with an error

The [LRS spec](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Communication.md#:~:text=The%20LRS%20MUST%20reject%20with%20400%20Bad%20Request%20status%20any%20requests%20that%20use%20any%20parameters%20which%20the%20LRS%20does%20not%20recognize%20in%20their%20intended%20context%20in%20this%20specification.%20(%20Note%3A%20LRSs%20MAY%20recognize%20and%20act%20on%20parameters%20not%20in%20this%20specification)) does not specify what should be done in such case : *LRSs MAY recognize and act on parameters not in this specification* 

So we should decide if we return a 200 or 400 response.

NB : [lrsql](https://github.com/yetanalytics/lrsql) returns a 400 in such case with the following body 
```
{
    "error": {
        "message": "Invalid Params for path: /xapi/statements",
        "params": {
            "toto": "2"
        }
    }
}
```

**Actual Behavior**
This query or any query using parameters not described in the specification returns a 500 error with the following server error : `TypeError: StatementParameters.__init__() got an unexpected keyword argument 'toto'`

**Steps to Reproduce**
1. GET : `<base_url>/xAPI/statements?toto=2`

**Environment**
- Ralph version: 3.8.0
- Platform: docker compose

**Comment by wilbrdt** [comment]
It should return a `400 Bad Request` for parameters unknown to Ralph indeed!
