### ISSUE TITLE
IRI check is not done on activity query parameter of /xAPI/statements 

### ISSUE THREAD

**Issue by lebrunthibault** [openfun/ralph#376]
## Bug Report

**Expected behavior/code**
The GET query : `/xAPI/statements?activity=toto` should return a 400 response with an error

The [LRS spec](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Communication.md#:~:text=400%20Bad%20Request%20%2D%20Indicates%20an%20error%20condition%20caused%20by%20an%20invalid%20or%20missing%20argument.%20The%20term%20%22invalid%20arguments%22%20includes%20malformed%20JSON%20or%20invalid%20Object%20structures.) specifies that invalid parameters should trigger a 400 response : 
So we should decide if we return a 200 or 400 response.

NB : [lrsql](https://github.com/yetanalytics/lrsql) returns a 400 in such case with the following body 
```
{
    "error": {
        "message": "Invalid Params for path: /xapi/statements",
        "params": {
            "activity": "toto"
        }
    }
}
```

**Actual Behavior**
This query or any query using parameters not described in the specification returns a 200 response with no statements

**Steps to Reproduce**
1. GET : `<base_url>/xAPI/statements?activity=toto`

**Environment**
- Ralph version: 3.8.0
- Platform: docker compose

**Comment by Leobouloc** [comment]
The specification you link to mentions "general guidance on HTTP error codes that **could** be returned".

FastAPI has a builtin 422 Unprocessable Entity. Perhaps we should stick to that ?
