### ISSUE TITLE
Implement `max_statements` for all backends

### ISSUE THREAD

**Issue by Leobouloc** [openfun/ralph#423]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
As reported in https://github.com/openfun/ralph/issues/418, it could be useful to have an option to limit the number of statements returned by the library backends. 

This will be implemented for `AsyncLRSHTTP` with https://github.com/openfun/ralph/pull/422 using the keyword `max_statements`. 

It would be nice to implement this option for other backends (ES, mongo, etc.)

**Comment by wilbrdt** [comment]
Done in #518
