### ISSUE TITLE
Add a LRSStatementsQuery pydantic model to validate LRS queries for the statements ressource

### ISSUE THREAD

**Issue by jmaupetit** [openfun/ralph#425]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
We need a more pedantic way to validate LRS queries than a simple generic one:

https://github.com/openfun/ralph/blob/a8342906d8504169a6ce2775c2e28d58608d59ed/src/ralph/backends/http/async_lrs.py#L38-L41

**Describe the solution you'd like**
Having a complete `LRSStatementsQuery` inspired from the `StatementParameters` dataclass would be lovely to implement such model.

https://github.com/openfun/ralph/blob/a8342906d8504169a6ce2775c2e28d58608d59ed/src/ralph/backends/database/base.py#L60-L82 

**Describe alternatives you've considered**
None.

**Discovery, Documentation, Adoption, Migration Strategy**
To avoid code duplication and since we don't need validation for the `StatementParameters` dataclass, we can define a single model and use pydantic's models `.construct()` method when validation is not required.

**Do you want to work on it through a Pull Request?**
It's your call. Tell me!

**Comment by Leobouloc** [comment]
I agree. 

Perhaps we could rename  `StatementParameters` to `RalphStatementsQuery`, and have it derive from the more general `LRSStatementsQuery` which only has the parameters specified by the xAPI specification.
