### ISSUE TITLE
Fix `www-authenticate` header

### ISSUE THREAD

**Issue by Leobouloc** [openfun/ralph#523]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
`www-authenticate` header should include a `realm` parameter which currently isn't the case (https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#basic_authentication_scheme)

Also, useful information. Multiple chalanges may be included in the header seperated by a comma (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate#syntax)

**Describe the solution you'd like**
Fix header generation to follow standards.

**Comment by wilbrdt** [comment]
We can have multiple challenges in one header separated by a comma indeed!
The mandatory `realm` seems to not be so implemented anymore (even if required) and it wouldn't be useful in Ralph as we don't have multiple protected spaces.
Closing this!
