### ISSUE TITLE
Scaled score is typed as int

### ISSUE THREAD

**Issue by lmaheo** [openfun/ralph#612]
## Bug Report

**Expected behavior/code**
I would expect `statement.result.score.scaled` to be of type `float` generally. Does the xAPI documentation specify that it should be an int? `int` casting often replaces scaled scores with a 0...

**Actual Behavior**
Currently `statement.result.score.scaled` is typed as `int`, so scores between 0 and 1 get crushed to 0.

**Steps to Reproduce**
1. Run
```python
from ralph.models.xapi.base.results import BaseXapiResultScore
print(BaseXapiResultScore.parse_obj({
    "raw": 1,
    "min": 0,
    "max": 2,
    "scaled": 0.5,
}))
```
2. See that the `scaled` value is 0 in this case, instead of 0.5 or Decimal('0.5') or something to the same effect.

**Environment**
- Ralph version: 3.9.0
- Platform: Linux Python 3.11.9

**Possible Solution**

I would replace the line [here](https://github.com/openfun/ralph/blob/e01cbeca485e7a5359313c50f21172e6ef3536c4/src/ralph/models/xapi/base/results.py#L26)
with :
~~`scaled: Optional[Annotated[int, Field(ge=-1, le=1)]] = None`~~
`scaled: Optional[Annotated[float, Field(ge=-1, le=1)]] = None`

**Comment by wilbrdt** [comment]
It's an error indeed! The [xAPI documentation](https://opensource.ieee.org/xapi/xapi-base-standard-documentation/-/blob/main/9274.1.1%20xAPI%20Base%20Standard%20for%20Content.md#5224-result) specifies that `scaled` is a decimal number between 0 and 1.
I see that you are using Ralph version `3.9.0`. Are you using Pydantic v1?
Asking to know if upgrading to a latest Ralph v5 version with a fix would be a problem for you.

**Comment by lmaheo** [comment]
I am indeed using pydantic v1, but that's OK!
I would welcome the fix, even if the migration to pydantic v2 is not possible right now :)
