### ISSUE TITLE
Correct docstring typos with endpoint for ralph documentation

### ISSUE THREAD

**Issue by quitterie-lcs** [openfun/ralph#65]
## Bug Report

**Expected behavior/code**
In Ralph documentation, command and models description sentences should end with a point.

**Actual Behavior**
Some of them are currently missing endpoints. 

**Steps to Reproduce**
1. Read `command` page from [Ralph documentation](https://openfun.github.io/ralph/)
2. Read `models` page from the upper documentation
3. Compare that some `command` and `models` are missing endpoints

**Environment**
- Ralph version: 1.1.0

**Possible Solution**
Recheck all docstrings and add enpoints if missing

**Comment by jmaupetit** [comment]
Initial report has been made in https://github.com/openfun/ralph/pull/60#pullrequestreview-597602680
