### ISSUE TITLE
Add support for the AWS Glacier backend

### ISSUE THREAD

**Issue by jmaupetit** [openfun/ralph#76]
## Purpose

A few cloud providers propose an Amazon Glacier-compatible cold storage service. It seems required to add support for this backend in Ralph.

## Proposal

Implement a new `glacier` backend using the [`boto`](https://github.com/boto/boto3) library. In a first implementation, we can consider this backend as write-only.

**Comment by quitterie-lcs** [comment]
With the upcoming plugin architecture, developers will be free to add backends that are necessary for them. As at FUN, we don't make use of this type of backend, this issue is closed.
